### ISSUE TITLE
Have all Github actions running on pull requests

### ISSUE THREAD

**Issue by biancagi** [pyre/pyre#97]
As of now, only the `pypi` github actions run on pull requests. However, it would be desirable that all github actions, including the `cmake` and `mm` ones, run on pull requests. 

I tried to implement this by modifying the following lines of `.github/workflows/cmake.yaml ` from
```
on:
  push:
    branches:
      - main 
```
into 
```
on:
  push:
    branches:
      - main 
  pull_request:
```
but this resulted in the error `fatal: reference is not a tree` when the runner would check out the pyre repository.
